######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 21 02:57:05 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainWindow.h scribblearea.h
SOURCES += main.cpp mainWindow.cpp scribblearea.cpp
