######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 28 12:31:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += character.h mainWindow.h scribblearea.h stroke.h
SOURCES += character.cpp main.cpp mainWindow.cpp scribblearea.cpp stroke.cpp
